### ISSUE TITLE
Test: Theming Bugs

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#350]
Examples of things to test:
- Are the correct banners and department names showing up for their respective department?
- ADA compliance - contrast of text on background
- Alignment and spacing of text and images
- Books layout
- Views styling

**Comment by kcleonardo** [comment]
- [x] ~~on the header, can we add a vertical line between Library and Library Administrative Services to separate them?~~
- [x] the image banner looks a bit pixelated on my screen (desi moved this to #356)

**Comment by dgallardo** [comment]
- [x] ~~Add padding in between paragraphs~~
- [x] ~~we need to lessen the width of the indentation before sub-topic items in the left side menu~~
- [x] ~~in top bar, align magnifying glass with search field - still doesn't look aligned? http://screencast.com/t/NMV9fjFvIQN~~
- [x] ~~adjust line height in lists to match the line height in the paragraphs http://screencast.com/t/XwIjxmeryZ~~

**Comment by dgallardo** [comment]
student job board:
- [x] ~~backgound color for rows should alternate white and #eee~~
- [x] remove extra search button http://screencast.com/t/fU1fjcdnMd (moved to #356)

student job posting:
- [x] ~~is it possible to move the content up to align with the top of the 'apply' button? http://screencast.com/t/xwfXaUnS~~

books:
- [x] ~~match font-size and color of text in the table of contents with font-size and color of text in side menus~~

LAS index page:
- [x] style Announcements view: http://screencast.com/t/kgxJgI31BC (moved to #356)
- [x] limit to 3 announcements in view (moved to #356)
- [x] ~~allow public users to view announcement content types~~
- [x] ~~use our general LAS theme for displaying individual announcements, like http://test-lhrdredesign.pantheon.berkeley.edu/about~~
- [x] ~~Show list of open student, staff and academic jobs in the right column. Limit to 3 for each. Order by last updated date.  Display job title, department and date last updated.~~

**Comment by dgallardo** [comment]
- [x] 
  ~~Style tables according to the table in the form repo mockup in LAS final > theme > mockups. This styling should apply to table views (e.g. form repo) and any tables we have in the content of our site (e.g. http://test-lhrdredesign.pantheon.berkeley.edu/lhrd/staff/classifications-by-bargaining-unit).~~

**Comment by dgallardo** [comment]
- [x] Style Staff Job: http://screencast.com/t/s3dZGzn173 ; and mockup is also in LAS final theme folder
- [x] style academic job: http://screencast.com/t/hIPHrmmT ; and mockup is in LAS final theme folder
- [x] style views for academic and staff jobs. mockups in folder
